[27-Nov-2021 03:41:14] ERROR [views.py:61] [TaskApp] LoginSubmitAPI Expecting value: line 1 column 1 (char 0) at 37
[27-Nov-2021 03:43:36] ERROR [views.py:58] [TaskApp] LoginSubmitAPI name 'sys' is not defined at 40
[27-Nov-2021 03:44:29] ERROR [views.py:59] [TaskApp] LoginSubmitAPI name 'sys' is not defined at 41
[27-Nov-2021 07:15:35] ERROR [views.py:151] [TaskApp] CreateUserAPI name 'User' is not defined at 143
[27-Nov-2021 16:00:09] ERROR [views.py:45] [TaskApp] Home Invalid block tag on line 122: 'task_obj.is_completed', expected 'empty' or 'endfor'. Did you forget to register or load this tag? at 39
[27-Nov-2021 16:10:08] ERROR [views.py:45] [TaskApp] Home Invalid block tag on line 167: 'endblock', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag? at 39
[27-Nov-2021 19:08:04] ERROR [views.py:45] [TaskApp] Home Could not parse the remainder: ': "d/m/Y"' from 'task_obj.deadline|date: "d/m/Y"' at 39
[27-Nov-2021 19:08:42] ERROR [views.py:45] [TaskApp] Home Could not parse the remainder: ': 'd/m/Y'' from 'task_obj.deadline|date: 'd/m/Y'' at 39
[27-Nov-2021 19:08:53] ERROR [views.py:45] [TaskApp] Home Could not parse the remainder: ': 'dmY'' from 'task_obj.deadline|date: 'dmY'' at 39
[27-Nov-2021 22:02:50] ERROR [views.py:46] [TaskApp] Home module 'datetime' has no attribute 'today' at 39
[27-Nov-2021 22:05:02] ERROR [views.py:222] [TaskApp] AddTaskAPI ['“on” value must be either True or False.'] at 214
[27-Nov-2021 23:12:40] ERROR [views.py:46] [TaskApp] Home 'custom_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz at 40
[28-Nov-2021 00:20:38] ERROR [views.py:58] [TaskApp] Home no such column: TaskApp_task.task_bucket_id at 40
